Cloud run pubsub integration
Wunderman-Thompson-COE/oculi pull request #13
Opened 2021-12-03 16:48 UTC by oslaru

This PR has two main changes:

* Fix object annotation plus truncate policy in Bigquery
* Add Cloud Run Pubsub integration

2021-12-05 15:32 UTC, kaaquist requested changes
A few minor tings.

2021-12-05 15:32 UTC, kaaquist commented on Dataflow/Dockerfile
> +FROM python:3.7
In content ai we use the `3.9-slim-buster`. It is not as large in data size. But I will leave to you to decide if we update.  👍

2021-12-05 15:32 UTC, kaaquist commented on Dataflow/pipeline/requirements_local.txt
> +google-cloud-videointelligence==1.8.0
why are we bumping this here down again?

2021-12-05 15:32 UTC, kaaquist commented on scripts/pubsub-cloud-run-intergration.sh
> +SUBSCRIPTION="pubsub-cloud-run-oculi-subscription"
let's remove this here and use args instead. (I know it is for local use, but then let's not commit it)
`$/pubsub-cloud-run-intergration.sh -a argument1 -b argument2 -c "argument 3"`
Link: https://unix.stackexchange.com/a/505342

2021-12-05 15:32 UTC, kaaquist commented on scripts/payload.json
> +}
Let's not commit this here. Customer info. Maybe it is time to make the repository private.

2021-12-06 13:11 UTC, oslaru commented on Dataflow/pipeline/requirements_local.txt
> +google-cloud-videointelligence==1.8.0
apache beam is not compatible with 2.5.1 yet,  but oculi doesnt use videointelligence inside apache beam (It calls videointelligence in first step and it starts the beam pipeline once it has all the data), the workaround is to use 1.8.0 in requirements_local.txt and later update to 2.5.1, the way I do in Dockerfile

2021-12-06 13:24 UTC, kaaquist approved these changes

2021-12-06 13:42 UTC, merged